# Generated by Django 3.2 on 2023-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paipu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField()),
                ('ref', models.CharField(max_length=200)),
                ('log', models.JSONField()),
                ('ratingc', models.CharField(max_length=100)),
                ('rule', models.JSONField()),
                ('lobby', models.IntegerField()),
                ('dan', models.JSONField()),
                ('rate', models.JSONField()),
                ('sx', models.JSONField()),
                ('name', models.JSONField()),
                ('title', models.JSONField()),
            ],
        ),
    ]
