# Generated by Django 3.2 on 2023-10-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumj', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paipu',
            name='players',
        ),
    ]
